export const categories = [
  {
    slug: 'music',
    name: 'Music',
    short: 'Music',
    image: '/assets/live-stage.jpg',
    accent: '#e5b95c',
    accentText: '#050617',
    headline: 'Live sets, cyphers, listening rooms, and artist-led drops.',
    description:
      'A premium lane for performances, DJ blocks, interviews, premieres, and city-led music culture with clear replay and rights language.',
    stats: ['61.4K live', '24 featured rooms', '$31.6K paid today'],
    tags: ['Cyphers', 'DJ rooms', 'Premieres', 'R&B', 'Rap'],
  },
  {
    slug: 'gaming',
    name: 'Gaming',
    short: 'Games',
    image: '/assets/gaming-desk.jpg',
    accent: '#2447ff',
    accentText: '#f8eedc',
    headline: 'Creator tournaments, ranked runs, side quests, and sponsor-safe heat.',
    description:
      'A Twitch-style discovery lane tuned for TAPN: high-energy rooms, clear trust scores, paid quests, and stronger creator ownership.',
    stats: ['44.8K live', '18 brackets', '92% positive chat'],
    tags: ['Tournaments', 'FPS', 'Sports', 'Variety', 'Retro'],
  },
  {
    slug: 'irl',
    name: 'IRL',
    short: 'IRL',
    image: '/assets/concert-crowd.jpg',
    accent: '#c1122f',
    accentText: '#f8eedc',
    headline: 'Street-level culture, events, food, fashion, and live field reports.',
    description:
      'IRL rooms built for momentum with guardrails: location safety, event passes, brand windows, and moderation escalation built in.',
    stats: ['39.7K live', '13 cities', '8 sponsor stacks'],
    tags: ['Events', 'Food', 'Fashion', 'Travel', 'Field reports'],
  },
  {
    slug: 'shows',
    name: 'Shows',
    short: 'Shows',
    image: '/assets/podcast-studio.jpg',
    accent: '#6d2ad8',
    accentText: '#f8eedc',
    headline: 'Talk formats, originals, watch parties, and premium hosted series.',
    description:
      'A schedule-forward programming lane for creators who think like networks: recurring segments, sponsors, clips, and protected chat.',
    stats: ['26.9K live', '11 originals', '99 trust average'],
    tags: ['Podcasts', 'Interviews', 'Watch parties', 'Panels', 'Originals'],
  },
  {
    slug: 'video',
    name: 'Video',
    short: 'Video',
    image: '/assets/creator-camera.jpg',
    accent: '#8b1e7a',
    accentText: '#f8eedc',
    headline: 'Premieres, short-form drops, film rooms, and creator-owned replays.',
    description:
      'Video drops sit beside live rooms so creators can premiere work, sell replay windows, and bring fans into the moment.',
    stats: ['18.5K live', '32 drops', '14 replay windows'],
    tags: ['Premieres', 'Film', 'Clips', 'Video essays', 'Behind the scenes'],
  },
];

export const channels = [
  {
    slug: 'late-night-atl-cypher',
    title: 'Late Night ATL Cypher',
    creator: 'Ari Lennox Ave',
    category: 'music',
    kind: 'Live stage',
    city: 'Atlanta',
    image: '/assets/live-stage.jpg',
    viewers: '48.2K',
    paid: '$18.4K',
    trust: 97,
    replay: 'Creator-owned replay',
    sponsor: '2 premium bids',
    chat: 'Warm',
    schedule: 'Tonight, 10 PM ET',
    description:
      'An after-hours performance room for vocalists, producers, DJs, and hosts. Fans buy passes, send tips, and replay the clean cut after the room closes.',
    tags: ['Cypher', 'R&B', 'Atlanta', 'Live stage'],
    accent: '#e5b95c',
    accentText: '#050617',
    chatMessages: [
      ['Mika', 'This hook is already a moment.'],
      ['Jules', 'Run the pocket back after the verse.'],
      ['TAPN Mod', 'Keep the room warm. No doxxing, no threats.'],
      ['Ari Lennox Ave', 'Second singer is coming up after this beat.'],
    ],
  },
  {
    slug: 'side-quest-sundays',
    title: 'Side Quest Sundays',
    creator: 'NoCapNova',
    category: 'gaming',
    kind: 'Creator tournament',
    city: 'Brooklyn',
    image: '/assets/gaming-desk.jpg',
    viewers: '21.8K',
    paid: '$7.9K',
    trust: 94,
    replay: 'Member replay',
    sponsor: 'Controller drop',
    chat: 'Active',
    schedule: 'Sunday, 7 PM ET',
    description:
      'A gaming bracket with creator teams, fan quests, channel-pass perks, and a sponsor meter that only unlocks after the room stays clean.',
    tags: ['Tournament', 'Variety', 'Creator cup', 'Brooklyn'],
    accent: '#2447ff',
    accentText: '#f8eedc',
    chatMessages: [
      ['NovaNation', 'Bracket is stacked tonight.'],
      ['Kojo', 'Need that controller drop.'],
      ['TAPN Desk', 'Sponsor quest unlocks at 95 trust.'],
      ['NoCapNova', 'Finals are subscriber-only replay.'],
    ],
  },
  {
    slug: 'the-green-room',
    title: 'The Green Room',
    creator: 'Zora Speaks',
    category: 'shows',
    kind: 'Talk format',
    city: 'Harlem',
    image: '/assets/podcast-studio.jpg',
    viewers: '16.5K',
    paid: '$5.3K',
    trust: 99,
    replay: 'Editorial cut',
    sponsor: '1 studio partner',
    chat: 'Protected',
    schedule: 'Weeknights, 8 PM ET',
    description:
      'A hosted studio show for artists, athletes, founders, and culture critics, packaged with clean clips and brand-safe inventory.',
    tags: ['Originals', 'Interview', 'Harlem', 'Talk'],
    accent: '#6d2ad8',
    accentText: '#f8eedc',
    chatMessages: [
      ['Nia', 'This sponsor read actually fits.'],
      ['Corey', 'Need the clip of that last answer.'],
      ['Zora Speaks', 'Questions from members in three minutes.'],
      ['TAPN Mod', 'Protected mode is on for guest segment.'],
    ],
  },
  {
    slug: 'lens-check-live',
    title: 'Lens Check Live',
    creator: 'KillaFrame',
    category: 'video',
    kind: 'Video drop',
    city: 'Los Angeles',
    image: '/assets/creator-camera.jpg',
    viewers: '12.1K',
    paid: '$3.8K',
    trust: 96,
    replay: 'Drop window',
    sponsor: 'Camera shop',
    chat: 'Clean',
    schedule: 'Friday, 9 PM PT',
    description:
      'A creator-camera room for premieres, breakdowns, gear talk, and short-film drops with paid replays and sponsor-safe product blocks.',
    tags: ['Premiere', 'Film', 'Camera', 'Los Angeles'],
    accent: '#8b1e7a',
    accentText: '#f8eedc',
    chatMessages: [
      ['FrameClub', 'The color grade is nasty.'],
      ['Lex', 'Can we get the lighting setup?'],
      ['KillaFrame', 'Gear list drops after the replay window.'],
      ['TAPN Desk', 'Clip requests are open.'],
    ],
  },
  {
    slug: 'block-party-replay',
    title: 'Block Party Replay',
    creator: 'Nia North',
    category: 'irl',
    kind: 'IRL event',
    city: 'New Orleans',
    image: '/assets/concert-crowd.jpg',
    viewers: '39.7K',
    paid: '$11.6K',
    trust: 95,
    replay: 'Event pass',
    sponsor: 'Local brand stack',
    chat: 'High energy',
    schedule: 'Saturday, 6 PM CT',
    description:
      'A city-led IRL event room with ticketed replay, local sponsors, field producers, and safety controls for location-aware streaming.',
    tags: ['IRL', 'Event', 'New Orleans', 'Culture'],
    accent: '#c1122f',
    accentText: '#f8eedc',
    chatMessages: [
      ['BayouLive', 'Camera two is catching everything.'],
      ['Tee', 'The food vendor cam is elite.'],
      ['Nia North', 'Location delay is on for safety.'],
      ['TAPN Mod', 'No private addresses in chat.'],
    ],
  },
  {
    slug: 'sunday-service-arcade',
    title: 'Sunday Service Arcade',
    creator: 'Saint Liv',
    category: 'gaming',
    kind: 'Retro ladder',
    city: 'Detroit',
    image: '/assets/gaming-desk.jpg',
    viewers: '9.4K',
    paid: '$2.2K',
    trust: 98,
    replay: 'Free VOD',
    sponsor: 'Arcade cabinet',
    chat: 'Chill',
    schedule: 'Sunday, 3 PM ET',
    description:
      'Retro games, music breaks, and a community ladder where fans can tip challengers into the bracket.',
    tags: ['Retro', 'Arcade', 'Detroit', 'Community'],
    accent: '#2447ff',
    accentText: '#f8eedc',
    chatMessages: [
      ['LivLoop', 'This score chase is personal now.'],
      ['Dre', 'Put me on the ladder next week.'],
      ['Saint Liv', 'Winner picks the next cabinet.'],
      ['TAPN Desk', 'Arcade bounty is live.'],
    ],
  },
  {
    slug: 'midnight-cut',
    title: 'Midnight Cut',
    creator: 'Maya Works',
    category: 'video',
    kind: 'Film room',
    city: 'Chicago',
    image: '/assets/creator-camera.jpg',
    viewers: '7.6K',
    paid: '$1.9K',
    trust: 97,
    replay: 'Member cut',
    sponsor: 'Post house',
    chat: 'Focused',
    schedule: 'Thursday, 11 PM ET',
    description:
      'A director-led edit room where members watch scenes, vote on cuts, and buy access to the final commentary replay.',
    tags: ['Film', 'Editing', 'Chicago', 'Members'],
    accent: '#8b1e7a',
    accentText: '#f8eedc',
    chatMessages: [
      ['CutRoom', 'The second take lands better.'],
      ['Maya Works', 'Voting opens after the sound pass.'],
      ['Rae', 'Can we clip the before and after?'],
      ['TAPN Mod', 'Spoiler mode stays on.'],
    ],
  },
  {
    slug: 'kitchen-table-live',
    title: 'Kitchen Table Live',
    creator: 'Chef Kemi',
    category: 'irl',
    kind: 'Food room',
    city: 'Houston',
    image: '/assets/concert-crowd.jpg',
    viewers: '11.2K',
    paid: '$4.1K',
    trust: 96,
    replay: 'Recipe pass',
    sponsor: 'Market partner',
    chat: 'Hungry',
    schedule: 'Wednesday, 7 PM CT',
    description:
      'A live cooking and culture room with recipe passes, local market sponsors, and clean replay chapters.',
    tags: ['Food', 'Houston', 'IRL', 'Recipe pass'],
    accent: '#c1122f',
    accentText: '#f8eedc',
    chatMessages: [
      ['KemiCrew', 'Drop the spice blend.'],
      ['Chef Kemi', 'Recipe pass goes up after plating.'],
      ['TAPN Desk', 'Sponsor coupon is pinned.'],
      ['Andre', 'That pan shot sold me.'],
    ],
  },
];

export const marketStats = [
  { value: '72%', label: 'creator rev share target' },
  { value: '24/7', label: 'safety desk concept' },
  { value: '4.8M', label: 'waitlist ambition' },
];

export const walletLines = [
  { label: 'Subscriptions', amount: '$8,920', value: 8920, color: '#2447ff' },
  { label: 'Tips', amount: '$4,416', value: 4416, color: '#e5b95c' },
  { label: 'Drops', amount: '$2,808', value: 2808, color: '#c1122f' },
  { label: 'Ads', amount: '$1,612', value: 1612, color: '#6d2ad8' },
];

export const revenueProducts = [
  ['Channel Passes', 'Paid rooms, event tickets, replay windows, and subscriber-only premieres.'],
  ['Instant Payouts', 'Tips, drops, ad splits, and sponsorship money sit in one transparent wallet.'],
  ['Rights Ledger', 'Creators see replay rights, split status, receipts, and deal history.'],
  ['Brand Market', 'Sponsors buy culture safely through trust scores and verified inventory.'],
];

export const publicPages = {
  about: {
    label: 'About',
    eyebrow: 'Company',
    title: 'Black entertainment, live and paid.',
    body:
      'TAPN is a premium live culture network for creators, fans, venues, and brands. It mixes Twitch utility, Kick-style monetization pressure, and BET-level cultural focus without treating safety as an afterthought.',
    cta: 'Browse live rooms',
    ctaTo: '/browse',
    stats: ['Creator-owned replays', 'Human review desk', 'Brand-safe heat'],
    panels: [
      ['Culture first', 'Music, gaming, IRL, shows, and video drops are treated as programming lanes, not generic content buckets.'],
      ['Money visible', 'Wallet, sponsor, tip, pass, and replay concepts stay close to the viewing surface.'],
      ['Review with receipts', 'High-impact safety decisions should show evidence, context, and appeal paths.'],
    ],
  },
  brand: {
    label: 'Brand',
    eyebrow: 'Brand resources',
    title: 'Royal signals for live culture.',
    body:
      'The TAPN look is built from obsidian navy, palace blue, crown crimson, imperial purple, parchment, and disciplined gold accents. The system should feel broadcast-ready, premium, and urgent.',
    cta: 'Open brand notes',
    ctaTo: '/brand',
    stats: ['Obsidian foundation', 'Royal signal colors', 'Hard lowercase mark'],
    panels: [
      ['Logo behavior', 'The play mark stays compact, blocky, and usable inside app chrome, cards, and channel surfaces.'],
      ['Color roles', 'Blue handles trust and action, red handles live heat, purple handles premium status, gold handles money and milestones.'],
      ['Voice', 'Protected, profitable, live, editorial, culturally fluent.'],
    ],
  },
  news: {
    label: 'News',
    eyebrow: 'News and press',
    title: 'Inside the TAPN build.',
    body:
      'A press-style page for launch updates, programming announcements, creator interviews, and product notes.',
    cta: 'See creator page',
    ctaTo: '/streamers',
    stats: ['Programming notes', 'Creator stories', 'Product drops'],
    panels: [
      ['TAPN Originals slate expands', 'A concept slate for interviews, cyphers, creator tournaments, and community-voted awards.'],
      ['Wallet-first rooms', 'A product note on keeping tips, passes, drops, sponsors, and replay revenue visible to creators.'],
      ['Safety desk principles', 'How evidence review, senior sign-off, and appeals can support expressive communities.'],
    ],
  },
  download: {
    label: 'Download',
    eyebrow: 'Apps',
    title: 'Watch live culture wherever the room moves.',
    body:
      'A launch-ready app page for mobile, console, and living-room surfaces. This pass shows the product story and download states without shipping native apps.',
    cta: 'Browse on web',
    ctaTo: '/browse',
    stats: ['Mobile streaming', 'TV casting', 'Replay access'],
    panels: [
      ['Mobile', 'Watch, chat, tip, and manage channel passes from a pocket-first interface.'],
      ['Console and TV', 'A living-room lane for shows, tournaments, replays, and event streams.'],
      ['Creator studio', 'Quick stream setup, payout visibility, and room safety controls on the go.'],
    ],
  },
  streamers: {
    label: 'Streamers',
    eyebrow: 'Creator program',
    title: 'Stream. Own. Earn.',
    body:
      'A creator landing page for artists, gamers, hosts, filmmakers, podcasters, and IRL operators who need money, audience, and protection in one place.',
    cta: 'Start a channel',
    ctaTo: '/channel/late-night-atl-cypher',
    stats: ['Passes', 'Drops', 'Tips', 'Replays'],
    panels: [
      ['Start a room', 'Pick a lane, set chat mode, choose replay rights, and publish with a clear trust posture.'],
      ['Earn in public', 'Put passes, drops, tips, sponsor blocks, and replay windows beside the stream.'],
      ['Build recurring formats', 'Turn rooms into shows, tournaments, cyphers, classes, and city-led events.'],
    ],
  },
  developers: {
    label: 'Developers',
    eyebrow: 'Developer program',
    title: 'Build tools for live culture.',
    body:
      'A developer-facing page for bots, overlays, analytics, safety tooling, stream integrations, and brand inventory tools.',
    cta: 'Read support docs',
    ctaTo: '/support',
    stats: ['Bots', 'Overlays', 'Webhooks', 'Bounties'],
    panels: [
      ['Create an app', 'Register a concept, define scopes, and keep creator data permissions explicit.'],
      ['Use event hooks', 'Plan around stream started, pass purchased, tip sent, clip requested, and safety review events.'],
      ['Launch with trust', 'Tools should respect room settings, moderation state, and creator payout visibility.'],
    ],
  },
  bounties: {
    label: 'Bounties',
    eyebrow: 'Builder bounties',
    title: 'Real wins for useful tools.',
    body:
      'A public bounty surface for stream overlays, moderation helpers, category widgets, creator analytics, and replay packaging tools.',
    cta: 'Open developer page',
    ctaTo: '/developers',
    stats: ['$2K overlay pool', '$5K safety pool', '$1K category pool'],
    panels: [
      ['Safety signal widget', 'Prototype a room overlay that shows trust score, mode, and escalation state.'],
      ['Replay chapter tool', 'Help creators package long streams into sellable chapters and clips.'],
      ['Sponsor inventory kit', 'Show brands where eligible rooms, categories, and windows are available.'],
    ],
  },
  shop: {
    label: 'Shop',
    eyebrow: 'Merch and drops',
    title: 'Drops that belong to the room.',
    body:
      'A lightweight shop concept for channel merch, event passes, replay windows, creator products, and TAPN brand goods.',
    cta: 'Browse categories',
    ctaTo: '/browse',
    stats: ['Channel merch', 'Event passes', 'Replay windows'],
    panels: [
      ['Creator drops', 'Limited products and digital drops tied to live moments.'],
      ['Event passes', 'Tickets and replay access for city-led IRL rooms and premium shows.'],
      ['TAPN goods', 'A restrained brand shop for launch merch and creator program kits.'],
    ],
  },
};

export const supportTopics = [
  ['Getting Started', 'Account setup, channel creation, basic streaming, and viewer controls.', '16 articles'],
  ['For Viewers', 'Following, chat modes, passes, replays, tips, and account preferences.', '12 articles'],
  ['For Streamers', 'OBS setup, stream keys, payouts, drops, rights, and replay windows.', '25 articles'],
  ['Monetization', 'Subscriptions, tips, pass sales, sponsor inventory, and payout concepts.', '17 articles'],
  ['Safety and Policies', 'Reports, appeals, moderation tools, trust scores, and evidence review.', '21 articles'],
  ['Troubleshooting', 'Playback, login, browser support, notifications, and billing issues.', '18 articles'],
  ['Developers and API', 'Apps, bots, webhooks, overlays, and integration guardrails.', '7 articles'],
  ['Transparency Reports', 'Moderation summaries, enforcement trends, and appeal outcomes.', '4 articles'],
];

export const faqs = [
  ['How does TAPN make creators money?', 'This prototype models passes, tips, drops, sponsors, ad splits, and replay windows as visible revenue lines.'],
  ['Is this connected to real streaming infrastructure?', 'No. This pass is a polished client-side product surface with mock player, chat, wallet, and content data.'],
  ['What makes TAPN different from Kick or Twitch?', 'TAPN centers Black entertainment programming, stronger creator ownership, visible monetization, and human safety review.'],
  ['Can brands sponsor rooms?', 'The product concept includes eligible-room inventory, trust scores, sponsor windows, and receipts for brand partners.'],
];

export const legalDocs = {
  guidelines: {
    label: 'Community Guidelines',
    title: 'Community Guidelines',
    sections: [
      ['Expressive rooms, real guardrails', 'TAPN rooms can be energetic, funny, critical, and culturally specific. Harassment, exploitation, doxxing, direct threats, and repeat abuse do not belong here.'],
      ['Graduated enforcement', 'Warnings, slow mode, room limits, demonetization, suspension, and removal should depend on context, evidence, and severity.'],
      ['Appeals', 'Creators and viewers should understand what happened, what evidence mattered, and how to request a second look.'],
    ],
  },
  dmca: {
    label: 'DMCA Policy',
    title: 'DMCA Policy',
    sections: [
      ['Rights reports', 'Rights holders should have a clear path to submit notices with contact information, work identification, and the allegedly infringing material.'],
      ['Creator receipts', 'Creators should see notice status, replay impact, and counter-notice options where applicable.'],
      ['Repeat issues', 'Repeated rights problems should trigger additional review before monetized replay access continues.'],
    ],
  },
  privacy: {
    label: 'Privacy Policy',
    title: 'Privacy Policy',
    sections: [
      ['Data categories', 'A production version would describe account data, stream activity, chat activity, payment metadata, device data, and safety reports.'],
      ['Use of data', 'Data should support streaming, discovery, payouts, trust and safety, support, product analytics, and creator tools.'],
      ['Controls', 'Users should be able to manage account information, preferences, notifications, and support requests.'],
    ],
  },
  terms: {
    label: 'Terms of Service',
    title: 'Terms of Service',
    sections: [
      ['Platform use', 'Terms should describe account eligibility, content responsibilities, monetization rules, and acceptable use.'],
      ['Creator revenue', 'A production version would define payout timing, platform fees, taxes, reversals, and sponsor inventory rules.'],
      ['Service changes', 'TAPN should reserve room to evolve features while giving creators reasonable notice for material monetization changes.'],
    ],
  },
  cookies: {
    label: 'Cookie Settings',
    title: 'Cookie Settings',
    sections: [
      ['Cookie categories', 'A production version would distinguish required cookies, analytics, preferences, and marketing technologies.'],
      ['Viewer control', 'Users should be able to choose optional categories and revisit those choices.'],
      ['Measurement', 'Analytics should help improve playback, discovery, support, and creator tools.'],
    ],
  },
  'partner-terms': {
    label: 'Partner Terms',
    title: 'Partner Terms',
    sections: [
      ['Program eligibility', 'Partner terms should define quality, safety, monetization, and programming expectations.'],
      ['Brand inventory', 'Partner rooms may unlock sponsor windows, featured placements, and premium replay packaging.'],
      ['Review standards', 'Repeated safety, rights, or payout issues can affect program status.'],
    ],
  },
  'bounty-terms': {
    label: 'Bounty Terms',
    title: 'Bounty Terms',
    sections: [
      ['Submission rules', 'Bounties should define deliverables, ownership, review timing, eligibility, and payment conditions.'],
      ['Security', 'Submissions must not misuse user data, bypass room controls, or weaken moderation.'],
      ['Selection', 'TAPN may select, reject, or request changes to submissions based on usefulness and fit.'],
    ],
  },
  'usage-policy': {
    label: 'API Usage Policy',
    title: 'API Usage Policy',
    sections: [
      ['Respect room settings', 'Apps, bots, and overlays should honor chat modes, moderation status, creator settings, and privacy limits.'],
      ['Rate limits', 'A production API would enforce rate limits and scope-based permissions.'],
      ['No hidden extraction', 'Developer tools should not scrape private data, impersonate creators, or obscure monetization receipts.'],
    ],
  },
};

export const footerGroups = [
  {
    title: 'Company',
    links: [
      ['About', '/about'],
      ['Brand', '/brand'],
      ['News and Press', '/news'],
      ['Download', '/download'],
    ],
  },
  {
    title: 'Resources',
    links: [
      ['Help and Support', '/support'],
      ['TAPN Streamers', '/streamers'],
      ['TAPN Developers', '/developers'],
      ['TAPN Bounties', '/bounties'],
      ['TAPN Shop', '/shop'],
    ],
  },
  {
    title: 'Legal',
    links: [
      ['Community Guidelines', '/guidelines'],
      ['DMCA Policy', '/dmca'],
      ['Privacy Policy', '/privacy'],
      ['Terms of Service', '/terms'],
      ['Cookie Settings', '/cookies'],
      ['Partner Terms', '/partner-terms'],
      ['Bounty Terms', '/bounty-terms'],
      ['API Usage Policy', '/usage-policy'],
    ],
  },
];
